using System.Diagnostics;
using System.Reflection;
using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;
using System.Runtime.Versioning;
using System.Security;
using IronPython.Modules;
using IronPython.Modules.Bz2;
using IronPython.Runtime;
using IronPython.Zlib;

[assembly: PythonModule("array", typeof(ArrayModule))]
[assembly: PythonModule("binascii", typeof(PythonBinaryAscii))]
[assembly: PythonModule("select", typeof(PythonSelect))]
[assembly: PythonModule("re", typeof(PythonRegex))]
[assembly: PythonModule("bz2", typeof(Bz2Module))]
[assembly: PythonModule("_winreg", typeof(PythonWinReg))]
[assembly: AssemblyFileVersion("2.7.3.1000")]
[assembly: AssemblyInformationalVersion("IronPython 2.7.3 final 0")]
[assembly: AssemblyCompany("IronPython Team")]
[assembly: AssemblyCopyright("© IronPython Contributors.")]
[assembly: PythonModule("_weakref", typeof(PythonWeakRef))]
[assembly: PythonModule("_warnings", typeof(PythonWarnings))]
[assembly: PythonModule("_subprocess", typeof(PythonSubprocess))]
[assembly: PythonModule("_ssl", typeof(PythonSsl))]
[assembly: PythonModule("_sre", typeof(PythonSRegEx))]
[assembly: PythonModule("_random", typeof(PythonRandom))]
[assembly: PythonModule("_functools", typeof(FunctionTools))]
[assembly: PythonModule("xxsubtype", typeof(xxsubtype))]
[assembly: PythonModule("time", typeof(PythonTime))]
[assembly: PythonModule("thread", typeof(PythonThread))]
[assembly: PythonModule("_struct", typeof(PythonStruct))]
[assembly: PythonModule("_heapq", typeof(PythonHeapq))]
[assembly: PythonModule("_ctypes_test", typeof(CTypesTest))]
[assembly: PythonModule("_ctypes", typeof(CTypes))]
[assembly: PythonModule("socket", typeof(PythonSocket))]
[assembly: PythonModule("_sha512", typeof(PythonSha512))]
[assembly: PythonModule("_sha256", typeof(PythonSha256))]
[assembly: PythonModule("_sha", typeof(PythonSha))]
[assembly: AssemblyTitle("IronPython.Modules")]
[assembly: AssemblyDescription("")]
[assembly: AssemblyConfiguration("Release")]
[assembly: AssemblyProduct("IronPython.Modules")]
[assembly: AssemblyTrademark("")]
[assembly: ComVisible(false)]
[assembly: Guid("20808534-55dd-4d10-b8f9-96e8f5a1af16")]
[assembly: SecurityTransparent]
[assembly: AllowPartiallyTrustedCallers]
[assembly: SecurityRules(SecurityRuleSet.Level1)]
[assembly: PythonModule("operator", typeof(PythonOperator))]
[assembly: PythonModule("nt", typeof(PythonNT))]
[assembly: PythonModule("_md5", typeof(PythonMD5))]
[assembly: PythonModule("math", typeof(PythonMath))]
[assembly: PythonModule("marshal", typeof(PythonMarshal))]
[assembly: PythonModule("_locale", typeof(PythonLocale))]
[assembly: PythonModule("_io", typeof(PythonIOModule))]
[assembly: PythonModule("_csv", typeof(PythonCsvModule))]
[assembly: PythonModule("itertools", typeof(PythonIterTools))]
[assembly: PythonModule("gc", typeof(PythonGC))]
[assembly: PythonModule("errno", typeof(PythonErrorNumber))]
[assembly: PythonModule("datetime", typeof(PythonDateTime))]
[assembly: PythonModule("cStringIO", typeof(PythonStringIO))]
[assembly: PythonModule("cPickle", typeof(PythonPickle))]
[assembly: PythonModule("copy_reg", typeof(PythonCopyReg))]
[assembly: PythonModule("_collections", typeof(PythonCollections))]
[assembly: PythonModule("_codecs", typeof(PythonCodecs))]
[assembly: PythonModule("_bisect", typeof(PythonBisectModule))]
[assembly: PythonModule("zlib", typeof(ZlibModule))]
[assembly: PythonModule("zipimport", typeof(ZipImportModule))]
[assembly: PythonModule("winsound", typeof(PythonWinsoundModule))]
[assembly: PythonModule("signal", typeof(PythonSignal))]
[assembly: PythonModule("mmap", typeof(MmapModule))]
[assembly: PythonModule("msvcrt", typeof(PythonMsvcrt))]
[assembly: PythonModule("cmath", typeof(ComplexMath))]
[assembly: AssemblyVersion("2.7.0.40")]
