namespace Firaxis.CivTech.CookerInterface;

public enum ICookerResult
{
	COOK_SUCCESS,
	COOK_FAILURE,
	COOK_PARTIAL_SUCCESS,
	COOK_FAILURE_BAD_PLATFORM,
	COOK_FAILURE_BAD_PATHS,
	COOK_FAILURE_NO_ASSET_ROOT,
	COOK_FAILURE_NO_PROJECT_CONFIG,
	COOK_FAILURE_NO_TEMPHEAP,
	COOK_FAILURE_NO_COOKER,
	COOK_FAILURE_PLATFORM,
	COOK_FAILURE_PACKAGE_DIR,
	COOK_FAILURE_CREATE_DIR
}
