using System.Diagnostics;
using System.Reflection;
using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;
using System.Runtime.Versioning;
using System.Security;
using System.Security.Permissions;
using System.Windows.Resources;

[assembly: AssemblyTitle("AssetEditor")]
[assembly: AssemblyDescription("")]
[assembly: AssemblyConfiguration("")]
[assembly: AssemblyCompany("")]
[assembly: AssemblyProduct("AssetEditor")]
[assembly: AssemblyCopyright("Copyright ©  2014")]
[assembly: AssemblyTrademark("")]
[assembly: ComVisible(false)]
[assembly: Guid("0117765b-81aa-4905-a68e-079a3d00f861")]
[assembly: AssemblyFileVersion("1.1.0.0")]
[assembly: AssemblyInformationalVersion("0")]
[assembly: AssemblyAssociatedContentFile("debugcontext_tools.xml")]
[assembly: AssemblyAssociatedContentFile("tooltips_tools.xml")]
[assembly: AssemblyAssociatedContentFile("helveticaneue.ttf")]
[assembly: AssemblyAssociatedContentFile("myriadpro-regular.otf")]
[assembly: AssemblyAssociatedContentFile("add_fx_to_tilebases.py")]
[assembly: AssemblyAssociatedContentFile("assign_geo_to_multipleassets.py")]
[assembly: AssemblyAssociatedContentFile("createcityblocks.py")]
[assembly: AssemblyAssociatedContentFile("create_assets_from_source_file.py")]
[assembly: AssemblyAssociatedContentFile("create_scaled_ui_textures.py")]
[assembly: AssemblyAssociatedContentFile("load_test_save.py")]
[assembly: AssemblyAssociatedContentFile("menusetupwizardcommand.py")]
[assembly: AssemblyAssociatedContentFile("multiassign_landmark_ao.py")]
[assembly: AssemblyAssociatedContentFile("nudge_triggers.py")]
[assembly: AssemblyAssociatedContentFile("preview_unit.py")]
[assembly: AssemblyAssociatedContentFile("remove_emissive.py")]
[assembly: AssemblyAssociatedContentFile("resaveassets.py")]
[assembly: AssemblyAssociatedContentFile("switchdecalstopillaged.py")]
[assembly: AssemblyAssociatedContentFile("update_asset_attachments.py")]
[assembly: AssemblyVersion("1.1.0.0")]
