namespace Firaxis.CivTech.AssetObjects;

public enum EntityChangeType
{
	ECT_GENERIC,
	ECT_COOK_PARAMETER_CHANGED,
	ECT_TRIGROUP_PARAMETER_CHANGED,
	ECT_MODEL_INSTANCE_CHANGED,
	ECT_MODEL_INSTANCE_REMOVED,
	ECT_ASSET_DSG_CHANGED,
	ECT_ASSET_ANIMATION_SET_CHANGED,
	ECT_ASSET_TIMELINE_SET_CHANGED,
	ECT_ASSET_TIMELINE_CHANGED,
	ECT_ASSET_TIMELINE_REMOVED,
	ECT_ATTACHMENT_CHANGED,
	ECT_ATTACHMENT_REMOVED,
	ECT_ATTACHMENT_COOK_PARAMETER_CHANGED,
	ECT_PARTICLE_EFFECT_ADDED,
	ECT_PARTICLE_EFFECT_REMOVED,
	ECT_LIGHT_DIRECTION_TAG_CHANGED,
	ECT_LIGHT_DIRECTION_TAG_REMOVED,
	ECT_BEHAVIOR_REMOVED,
	ECT_BEHAVIOR_ADDED,
	ECT_SPLINE_VERTEX_CHANGED,
	ECT_COUNT
}
