namespace Firaxis.CivTech.AssetPreviewer;

public enum KnobType
{
	KT_FUNCTION,
	KT_VALUE,
	KT_VALUE_INT,
	KT_VALUE_BOOL,
	KT_VALUE_FLOAT,
	KT_VALUE_COLOR,
	KT_VALUE_STRING,
	KT_RANGE,
	KT_RANGE_INT,
	KT_RANGE_FLOAT,
	KT_CONTAINER,
	KT_CONTAINER_INT,
	KT_CONTAINER_FLOAT,
	KT_CONTAINER_COLOR,
	KT_CONTAINER_STRING,
	KT_VALUE_ENTITY
}
